# Generated by Django 2.2 on 2019-07-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
